<?php
declare(strict_types=1);

namespace Test\LFApi;

use GuzzleHttp\Client;
use JavaReact\LFApi\Balance;
use Monolog\Logger;

/**
 * Class OrderTest
 * @package Test\LFApi
 * @internal
 * @covers \JavaReact\LFApi\Order
 */
class BalanceTest extends BaseTest
{
    /** @var Balance */
    protected $balance;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $logger = new Logger("stdout");
        $logger->pushHandler(new StdoutHandler());
        $this->balance = new Balance('appid', 'appkey', function () {
            return new Client([
                "base_uri" => \JavaReact\LFApi\Client::TEST_GATEWAY,
            ]);
        }, $logger);
        $this->isDebug = true;//输出结果
    }

    public function testBalanceGet()
    {
        $response = $this->balance->balanceGet();
        $this->dump($response);
        $this->assertSame(200, $response->getStatusCode());
        $this->assertSame(true, $response->isSuccess());
        $this->assertSame('15020190001', $response->result("api_id"));
    }
}